### ISSUE TITLE
run Chrome

### ISSUE THREAD

**Issue by quochuynh67** [redleafsofts/flutter_ffmpeg_wasm#5]
Could you help me about this issue?

[info] run FS.writeFile test_render.mp4 <4114050 bytes binary file>
Error: ffmpeg.wasm is not ready, make sure you have completed load().
https://unpkg.com/@ffmpeg/ffmpeg@0.11.6/dist/ffmpeg.min.js 1:8428   906
https://unpkg.com/@ffmpeg/ffmpeg@0.11.6/dist/ffmpeg.min.js 1:21498  r
https://unpkg.com/@ffmpeg/ffmpeg@0.11.6/dist/ffmpeg.min.js 1:12040  352
https://unpkg.com/@ffmpeg/ffmpeg@0.11.6/dist/ffmpeg.min.js 1:21498  r
https://unpkg.com/@ffmpeg/ffmpeg@0.11.6/dist/ffmpeg.min.js 1:22419  <fn>
https://unpkg.com/@ffmpeg/ffmpeg@0.11.6/dist/ffmpeg.min.js 1:22427  <fn>
https://unpkg.com/@ffmpeg/ffmpeg@0.11.6/dist/ffmpeg.min.js 1:189    <fn>
https://unpkg.com/@ffmpeg/ffmpeg@0.11.6/dist/ffmpeg.min.js 1:193    <fn>

**Comment by sarankumar-ns** [comment]
Hi, @quochuynh67 You need to load ffmpeg before calling any method by using the `load()` method. Make sure to `await` for this to load successfully. It will be helpful If you shared your code implementation.
