### ISSUE TITLE
Reference error: Can't find variable SharedArrayBuffer

### ISSUE THREAD

**Issue by lecletest** [redleafsofts/flutter_ffmpeg_wasm#9]
Hi @sarankumar-ns  when I run debug it works well, and then I deploy to hosting, it does not work anymore, and this `Reference error: Can't find variable SharedArrayBuffer` appear

**Comment by sarankumar-ns** [comment]
Can you provide minimal steps to reproduce the bug?

**Comment by pintu-elaunch** [comment]
I'm facing the same issue for production builds. 
<img width="760" alt="image" src="https://github.com/redleafsofts/flutter_ffmpeg_wasm/assets/106513455/6f9ac54d-b4b8-4197-8caa-13b8c2dbfd43">

For regenerating issue you can create web build and run it locally using python: `python3 -m http.server`

**Comment by ch1025540473** [comment]
> I'm facing the same issue for production builds. <img alt="image" width="760" src="https://private-user-images.githubusercontent.com/106513455/281032148-6f9ac54d-b4b8-4197-8caa-13b8c2dbfd43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzOTg4NDcsIm5iZiI6MTcwMTM5ODU0NywicGF0aCI6Ii8xMDY1MTM0NTUvMjgxMDMyMTQ4LTZmOWFjNTRkLWI0YjgtNDE5Ny04Y2FhLTEzYjhjMmRiZmQ0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQwMjQyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTk5NzUzNzRlYmU0ZGFlNmQxMjQ0MjM0YjlhZjhlZDM2MjQ0ZTJmZDY1MjUzZDE0MjAwOTA0MDE5MGFlMmY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AXzOcCDz9JtnjKDsGhDF8Ksn-wIvirf-r7wLxdSPxIo">
> 
> For regenerating issue you can create web build and run it locally using python: `python3 -m http.server`. Need to run this command in build/web folder.

excuse me , has this problem been solved?

**Comment by sarankumar-ns** [comment]
Hi @lecletest,
Make sure you set the headers correctly in production.

See the example at https://github.com/redleafsofts/flutter_ffmpeg_wasm/blob/main/example/firebase.json and read the document for deployment in Readme.
